name : Bug报告
description: 在使用插件时遇到了问题
title: 你发现的问题
labels: ["bug","待查看","优先级低"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您发现问题，请您起一个能清晰概括问题的标题。

        >[!CAUTION]
        >请不要在一个issue中提出多个问题，一个issue只对应一个问题。
        >请不要在issue里提出无关此issue的的问题
        >请不要在issue里包含非法字符！

        >[TIP]
        如果您不知道如何有效、精准地表述，我们建议您先阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
  - type: checkboxes
    id: checkbox
    attributes:
      label: 请确认以下事项
      description: 请在提交issue前仔细阅读并确认以下事项
      options:
        - label: 我确认在[当前issues](https://github.com/lihansen136/ClassIsland-Timed-Alert-Floater/issues?q=is%3Aissue%20label%3Abug)里没有重复的问题并且Also I'm updated to [the latest version](https://github.com/lihansen136/ClassIsland-Timed-Alert-Floater/releases)
          required: true        
        - label: 我已经仔细查看过内容，并知道这个选项不用勾选
          required: false
        - label: 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。
          required: true
  - type: markdown
    id: exception
    attributes:
      value: |
        ## Bug信息

        描述您遇到的 Bug。您可以附上截图、录屏、堆栈跟踪、日志等材料，便于开发者追踪问题。**您可以阅读[此处的文档](https://docs.classisland.tech/app/reporting-issue) 来了解如何收集跟踪错误需要的信息。**

        > [!note]
        > 上传附件时**请优先使用 GitHub 的附件系统上传附件**，将需要上传的附件粘贴或拖动到撰写区域即可上传。多个文件可打包为 zip 格式后上传。**尽量避免使用需要登陆或安装客户端才能接收附件的网盘（如\*度网盘、\*克网盘、1\*3网盘等）上传附件**，以避免开发者因不具有对应网盘客户端或账户而延误问题诊断。

        > [!warning]
        > 请不要在issue里包含非法字符！
        > 请不要在issue里包含任何的个人信息，包括但不限于：QQ号、手机号、邮箱地址、姓名、昵称、头像、头像链接、用户名、密码、身份证号、银行卡号、地址、个人信息等。
  - type: input
    id: excepted
    attributes:
      label: 期望的行为
      description: 详细的描述你期望发生的行为，突出与目前（可能不正确的）行为的不同。
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 实际结果
      description: 实际发生的行为。
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        详细描述要怎么操作才能再次触发这个 Bug。
      placeholder: |
        1. 首先……
        2. 然后……
        3. ……
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: 堆栈跟踪（可选）
      description: 如果在遇到这个 Bug 时发生了崩溃（弹出崩溃提示），或者产生了错误日志，请将产生的堆栈跟踪信息粘贴到此处，便于开发者定位 Bug。
      render: shell
  - type: input
    id: app_version
    attributes:
      label: 应用版本
      description: 您当前使用的 ClassIsland 版本号，可以在【应用设置】->【关于 ClassIsland】中查看。
      placeholder: 如：1.3.2.0-Firefly-e921904(dev)
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: 插件版本
      description: 您当前使用的 插件 版本号。
      placeholder: 如：0.0.0.1-beta
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: 操作系统版本
      description: |
        您当前使用的 Windows 操作系统版本，可以运行 `winver.exe` 查看。
        如果您不能肯定此 Bug 与操作系统无关，请填写此项。
      placeholder: 如：10.0.22000.0
  - type: input
    id: hardware_version
    attributes:
      label: 硬件版本
      description: |
        您当前使用的 Windows 操作系统，可以运行 `dxdiag` 查看硬件版本。
        如果您不能肯定此 Bug 与硬件无关，请填写此项，可以截屏上传或文字上传。
      placeholder: 如：CPU:Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  - type: checkboxes
    id: revision
    attributes:
      label: 最后一步
      description: 回顾您的回答
      options:
        - label: 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。
          required: true
